#!/bin/bash
[ ! -d "jarlib" ] && echo "You need to download dependencies as jar file in to the directory 'jarlib'" && mkdir jarlib && exit 1

if [ "$#" -eq 1 ]; then
        JAVA=".java"
        javac -classpath ".:jarlib/*"  "$1$JAVA"
        java -jar "jarlib/junit-platform-console-standalone-1.6.3.jar" -f "$1"
fi

