#!/bin/bash
if [ "$#" -eq 1 ]; then
	JAVA=".java"
	compile -o "$1$JAVA"
	exej "$1"
fi

while :; do
    case $1 in
        -h|--help) echo "With that command you compile and run a java code
	This command needs only one argument.
	-cp is equivalent in java right, first argument is the path of the jar file and the second argument is the java class"            
        ;;
   	-cp) JAVA=".java"
	     compile -o "$3$JAVA"
	     cd "executablejava"
	     java -cp .:../$2 $3
	     cd ".."
	;;
 *) break
    esac
    shift
done
